const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Blackground: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Plataforma: 0},
	{Fixar: 0},
	{Noel: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{Senóide: 0},
	{presente: 0},
	{Âncora: 0},
	{pontuação: 0},
	{ação: 0},
	{inimigo1: 0},
	{caixote: 0},
	{cuboGelo: 0},
	{marcador: 0},
	{cristal: 0},
	{casaDeNeve: 0},
	{proximaFase: 0},
	{terminoDaFase: 0},
	{Áudio: 0},
	{Sprite: 0},
	{Botão: 0},
	{resgate: 0},
	{fim: 0},
	{reiniciar: 0},
	{Texto: 0},
	{Sprite2: 0},
	{inimigo2: 0},
	{Sprite3: 0},
	{pontos: 0}
];

self.InstanceType = {
	Blackground: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Plataforma: class extends self.ITiledBackgroundInstance {},
	Noel: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	presente: class extends self.ISpriteInstance {},
	pontuação: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	caixote: class extends self.ITiledBackgroundInstance {},
	cuboGelo: class extends self.ITiledBackgroundInstance {},
	marcador: class extends self.ISpriteInstance {},
	cristal: class extends self.ISpriteInstance {},
	casaDeNeve: class extends self.ISpriteInstance {},
	proximaFase: class extends self.ISpriteInstance {},
	terminoDaFase: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	resgate: class extends self.ITextInstance {},
	fim: class extends self.ITextInstance {},
	reiniciar: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}